### ISSUE TITLE
创建了账套， 仅录入一笔库存现金期初，在科目余额表中查询不到

### ISSUE THREAD

**Issue by mrshelly** [antdesigner/accountcore#13]
是因为科目余额表的计算是在凭证录入时才触发的吧？

**Comment by antdesigner** [comment]
在没有选择期间的情况下,默认查询范围是1970年初到9999年底.
如何你的启用期初是2019年7月份,你应该选择该2019年7为查询开始期间.

**Comment by antdesigner** [comment]
科目余额表的期初余额反映的是查询期间的开始日期当月的月初余额

**Comment by antdesigner** [comment]
录入凭证的时候,如果在当月涉及的科目没有发生,会在余额表(accouncore_accouts_balance)里插入一条记录.而科目的每条启用期初在该表里有单独的一条记录,用isbegining来区分
