### ISSUE TITLE
大批量操作创建凭证时， 更新科目余额出错。

### ISSUE THREAD

**Issue by mrshelly** [antdesigner/accountcore#19]
见图:
2核 2G 40G vmware linux ubuntu amd64 server 虚拟机测试时

![image](https://user-images.githubusercontent.com/73540/62102376-57a44780-b2cb-11e9-842d-66d6e20450d8.png)

**Comment by mrshelly** [comment]
继续  PO:

![image](https://user-images.githubusercontent.com/73540/62109545-16b62e00-b2df-11e9-9b50-be21ba4a181b.png)

**Comment by antdesigner** [comment]
这正是担心的问题.后续优化必须首要解决这个问题

**Comment by antdesigner** [comment]
你有什么好的方法来解决这个问题

**Comment by mrshelly** [comment]
模拟 3个人看报表， 1个人做凭证的量， 10用户同时在线，每秒并发4的情况下测试的结果

![image](https://user-images.githubusercontent.com/73540/62188800-0fa32480-b3a0-11e9-8439-5e1b1e52e3a2.png)

**Comment by antdesigner** [comment]
这个工具没接触过,后面要向你学习

**Comment by mrshelly** [comment]
关于科目余额计算， 这样设计你看一下：

![image](https://user-images.githubusercontent.com/73540/62342787-b3184480-b51a-11e9-95f9-a670f348db5d.png)

**Comment by antdesigner** [comment]
什么时候触发计算

**Comment by mrshelly** [comment]
开启 works = 3  
20用户并发 4

![image](https://user-images.githubusercontent.com/73540/62821494-70a0d880-bba8-11e9-9ded-ca97683d8b42.png)

**Comment by antdesigner** [comment]
这次有没有出现 could not serialize access to concurrent update这个错误?

**Comment by antdesigner** [comment]
@mrshelly  能不用新在新增修改凭证的时候,用新的进程更新科目余额表,按队列方式处理更新科目余额表的并发?

**Comment by antdesigner** [comment]
> 关于科目余额计算， 这样设计你看一下：
> 
> ![image](https://user-images.githubusercontent.com/73540/62342787-b3184480-b51a-11e9-95f9-a670f348db5d.png)

你给的cron方案一个是只能1分钟执行一次.时间长了.
线程的方式处理,在多进程下可能会有问题,这点我不确定.
按照目前的算法,用后台任务方式,预期新增,修改,删除会带来很多冲突要解决,难一保证科目余额表的数据准确

**Comment by mrshelly** [comment]
> > 关于科目余额计算， 这样设计你看一下：
> > ![image](https://user-images.githubusercontent.com/73540/62342787-b3184480-b51a-11e9-95f9-a670f348db5d.png)
> 
> 你给的cron方案一个是只能1分钟执行一次.时间长了.
> 线程的方式处理,在多进程下可能会有问题,这点我不确定.
> 按照目前的算法,用后台任务方式,预期新增,修改,删除会带来很多冲突要解决,难一保证科目余额表的数据准确

两个点触发的。 一个是靠系统 cron 触发， 即最小粒度为 1min  另一个是每次业务凭证生成时的一次触发调用。本身cron 是另起线/进程的， 所以是异步方式的。 
我上面的图讲的就是你所说的新的线/进程进行余额表更新。

**Comment by antdesigner** [comment]
已经加锁
