### ISSUE TITLE
默认凭证列表页未分页， 导致进入凭证列表页面无响应

### ISSUE THREAD

**Issue by mrshelly** [antdesigner/accountcore#20]
菜单：
    会计 -> 记账凭证 -> 凭证列表

![image](https://user-images.githubusercontent.com/73540/62102854-101ebb00-b2cd-11e9-9694-cff2d82e4eff.png)

**Comment by mrshelly** [comment]
确认了一下 action 是有限制 limit 80 条记录的。怀疑是js处理影响了 action limit 参数。

**Comment by antdesigner** [comment]
这个被我人为在views.xml的相关视图设置成了9999,考虑到完整展现一个月的.
另外凭证列表目前采用的是字段拼接成htnl格式在前端展现,这应该也是一个原因.
你大概查询了有多少少条记录?

**Comment by mrshelly** [comment]
> 这个被我人为在views.xml的相关视图设置成了9999,考虑到完整展现一个月的.
> 另外凭证列表目前采用的是字段拼接成htnl格式在前端展现,这应该也是一个原因.
> 你大概查询了有多少少条记录?

右上角 凭证数 6901

**Comment by antdesigner** [comment]
已修改为每页300
