### ISSUE TITLE
科目余额表 期末余额为负时，余额方向存在问题

### ISSUE THREAD

**Issue by mrshelly** [antdesigner/accountcore#28]
RT
![image](https://user-images.githubusercontent.com/73540/62404565-d816c100-b5c7-11e9-9f7d-a148efabb6ca.png)

**Comment by antdesigner** [comment]
会计上是科目余额按照科目的设置的余额方向显示的,如果科目默认是借方余额,即使是余额在贷方,也应该转为借方负数.不是错误,是一种处理方式
