### ISSUE TITLE
给凭证打印添加发票大小的纸张支持

### ISSUE THREAD

**Issue by antdesigner** [antdesigner/accountcore#85]
奖励：3元 
保底 0.5元
人数：3人
时限：2019年10月10日前
[点击访问需求文档](https://docs.qq.com/doc/DUUt4ZkJEWERjTmJU)

**Comment by antdesigner** [comment]
QQ：285411957

**Comment by leangjia** [comment]
已提PR，略表支持。

**Comment by antdesigner** [comment]
#86
