### ISSUE TITLE
新增加报表模板自动生成全球唯一码

### ISSUE THREAD

**Issue by antdesigner** [antdesigner/accountcore#87]
奖励：5元 
保底 0.5元
人数：3人
时限：2019年10月20日前
[点击访问需求文档](https://docs.qq.com/doc/DUUN1TmNUWFplb2Rp)
[我参与的的Accountcore For Odoo（github悬赏） ](https://docs.qq.com/doc/DUWJCY2JlWWd4d3BXl)

**Comment by yhx5773489** [comment]
QQ：42188140

**Comment by antdesigner** [comment]
👍 等待复核

**Comment by antdesigner** [comment]
🥇 通过
